# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import pvz_pb2 as pvz__pb2

GRPC_GENERATED_VERSION = "1.71.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in pvz_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class PVZServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPVZList = channel.unary_unary(
            "/pvz.v1.PVZService/GetPVZList",
            request_serializer=pvz__pb2.GetPVZListRequest.SerializeToString,
            response_deserializer=pvz__pb2.GetPVZListResponse.FromString,
            _registered_method=True,
        )


class PVZServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPVZList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PVZServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetPVZList": grpc.unary_unary_rpc_method_handler(
            servicer.GetPVZList,
            request_deserializer=pvz__pb2.GetPVZListRequest.FromString,
            response_serializer=pvz__pb2.GetPVZListResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "pvz.v1.PVZService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("pvz.v1.PVZService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class PVZService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPVZList(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pvz.v1.PVZService/GetPVZList",
            pvz__pb2.GetPVZListRequest.SerializeToString,
            pvz__pb2.GetPVZListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
